/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.2/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    implementation("org.mongodb:mongodb-driver-sync:5.1.1")
    implementation("org.mongodb.spark:mongo-spark-connector_2.13:10.3.0")
    implementation("org.mongodb:mongodb-crypt:1.8.0")
    implementation("org.apache.spark:spark-sql_2.13:3.5.1")

    // Make slf4j quiet
    implementation("org.slf4j:slf4j-nop:1.7.36")
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit Jupiter test framework
            useJUnitJupiter("5.9.2")
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(8))
    }
}


application {
    // Define the main class for the application.
    mainClass.set("demo.App")
}
